version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - sphinx-apidoc -T -M -o docs/api src/ "*/tests"

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements/requirements-dev.txt
    - requirements: requirements/requirements.logcollector.txt
    - requirements: requirements/requirements.prefilter.txt
    - requirements: requirements/requirements.inspector.txt
    - requirements: requirements/requirements.detector.txt
    - requirements: requirements/requirements.train.txt

sphinx:
  configuration: docs/conf.py
