version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements-dev.txt
    - requirements: requirements.logcollector.txt
    - requirements: requirements.prefilter.txt
    - requirements: requirements.inspector.txt

sphinx:
  configuration: docs/conf.py
