logging:
  debug: true

heidgaf:
  lc:
    logserver:
      hostname: 172.27.0.8
      portin: 9998
      portout: 9999
      max_number_of_connections: 5

kafka:
  brokers:
    - hostname: 172.27.0.3
      port: 8097
    - hostname: 172.27.0.4
      port: 8098
    - hostname: 172.27.0.5
      port: 8099

  consumer:
    group_id: my_group

  batch_sender:
    batch_size: 1000
    batch_timeout: 5.0
