logging:
  debug: false

heidgaf:
  lc:
    logserver:
      hostname: 172.27.0.8
      port_in: 9998
      port_out: 9999
      max_number_of_connections: 1000

  collector:
    valid_status_codes: ["NOERROR", "NXDOMAIN"]
    valid_record_types: ["A", "AAAA"]

kafka:
  brokers:
    - hostname: 172.27.0.3
      port: 8097
    - hostname: 172.27.0.4
      port: 8098
    - hostname: 172.27.0.5
      port: 8099

  consumer:
    group_id: my_group

  batch_sender:
    batch_size: 1000
    batch_timeout: 5.0
