define: &zeek_http_topic "my_http_topic"
define: &zeek_dns_topic "my_dns_topic"
define: &zeek_dns_topic_2 "my_second_dns_topic"


logging:
  base:
    debug: false
  modules:
    log_storage.logserver:
      debug: false
    log_collection.collector:
      debug: false
    log_collection.batch_handler:
      debug: false
    log_filtering.prefilter:
      debug: false
    data_inspection.inspector:
      debug: false
    data_analysis.detector:
      debug: false

pipeline:
  log_storage:
    logserver:
      input_file: "/opt/file.txt"

  log_collection:
    collector:
      valid_logline_formats:
        dns:
          dga_format:
            - [ "ts", Timestamp, "%Y-%m-%dT%H:%M:%S" ]
            - [ "status_code", ListItem, [ "NOERROR", "NXDOMAIN" ], [ "NXDOMAIN" ] ]
            - [ "client_ip", IpAddress ]
            - [ "dns_server_ip", IpAddress ]
            - [ "domain_name", RegEx, '^(?=.{1,253}$)((?!-)[A-Za-z0-9-]{1,63}(?<!-)\.)+[A-Za-z]{2,63}$' ]
            - [ "record_type", ListItem, [ "A", "AAAA" ] ]
            # - [ "response_ip", IpAddress ]
            - [ "size", RegEx, '^\d+b$' ]

    batch_handler:
      batch_size: 10000
      batch_timeout: 30.0
      subnet_id:
        ipv4_prefix_length: 24
        ipv6_prefix_length: 64

  data_inspection:
    inspector:
      mode: univariate # multivariate, ensemble
      # Only used when mode is set to ensemble
      ensemble:
        model: WeightEnsemble
        module: streamad.process
        model_args:
      models:
        - model: ZScoreDetector
          module: streamad.model
          model_args:
            is_global: false
      anomaly_threshold: 0.01
      score_threshold: 0.5
      time_type: ms
      time_range: 20

  data_analysis:
    detectors:
      - name: "RF - DGA detector"
        model: rf # XGBoost
        checksum: ba1f718179191348fe2abd51644d76191d42a5d967c6844feb3371b6f798bf06
        base_url: https://heibox.uni-heidelberg.de/d/0d5cbcbe16cd46a58021/
        threshold: 0.5
        zeek_topic: *zeek_dns_topic_2 

  monitoring:
    clickhouse_connector:
      batch_size: 50  # do not set higher
      batch_timeout: 2.0


  zeek:
    sensors:
      zeek1:
        static_analysis: true
        protocol_to_topic:
          #- http: 
          #  - *zeek_http_topic
          - dns: 
            - *zeek_dns_topic
          #  - *zeek_dns_topic_2
        interfaces:
          - enx84ba5960ffe6
      zeek2: 
        static_analysis: false # default
        protocol_to_topic:
          - http: 
            - *zeek_http_topic
          - dns: 
            - *zeek_dns_topic
        interfaces: 
          - eth0
          - dummy
      zeek3:
        static_analysis: true
        protocol_to_topic:
          - http: 
            - *zeek_http_topic
          - dns: 
            - *zeek_dns_topic

environment:
  kafka_brokers:
    - hostname: kafka1
      port: 8097
      node_ip: 192.168.175.69
    - hostname: kafka2
      port: 8098
      node_ip: 192.168.175.69
    - hostname: kafka3
      port: 8099
      node_ip: 192.168.175.69
  kafka_topics_prefix:
    pipeline:
      logserver_in: "pipeline-logserver_in"
      logserver_to_collector: "pipeline-logserver_to_collector"
      batch_sender_to_prefilter: "pipeline-batch_sender_to_prefilter"
      prefilter_to_inspector: "pipeline-prefilter_to_inspector"
      inspector_to_detector: "pipeline-inspector_to_detector"
  monitoring:
    clickhouse_server:
      hostname: clickhouse-server
