logging:
  debug: false

heidgaf:
  logserver:
    hostname: 172.27.0.8
    port_in: 9998
    port_out: 9999
    max_number_of_connections: 1000
    listen_on_topic: "LogServer"

  collector:
    valid_status_codes: [ "NOERROR", "NXDOMAIN" ]
    valid_record_types: [ "A", "AAAA" ]

  prefilter:
    relevant_types: [ "NXDOMAIN" ]

  inspector:
    mode: univariate # multivariate, ensemble
    model: ZScoreDetector
    model_args:
      is_global: false
    module: streamad.model
    threshold: 4
    time_type: ms
    time_range: 1

  detector:
    model: xg # XGBoost
    path: https://heibox.uni-heidelberg.de/d/0d5cbcbe16cd46a58021/

  subnet:
    subnet_bits: 24

kafka:
  brokers:
    - hostname: 172.27.0.3
      port: 8097
    - hostname: 172.27.0.4
      port: 8098
    - hostname: 172.27.0.5
      port: 8099

  consumer:
    group_id: my_group

  batch_sender:
    batch_size: 1000
    batch_timeout: 20.0
