version: "3.9"

volumes:
  redis:
  heidgaf:

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  heidgaf:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]