include:
  - "docker-compose.kafka.yml"

services:

  logcollector:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.logcollector
      network: host
    restart: "unless-stopped"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    networks:
      heidgaf:
        ipv4_address: 172.27.0.7
    memswap_limit: 768m
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512m
        reservations:
          cpus: '1'
          memory: 256m

  logserver:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.logserver
      network: host
    restart: "unless-stopped"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    networks:
      heidgaf:
        ipv4_address: 172.27.0.8
    memswap_limit: 768m
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512m
        reservations:
          cpus: '1'
          memory: 256m


  inspector:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.inspector
      network: host
    restart: "unless-stopped"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    networks:
      heidgaf:
        ipv4_address: 172.27.0.6
    deploy:
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 512m
        reservations:
          cpus: '1'
          memory: 256m

  prefilter:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.prefilter
      network: host
    restart: "unless-stopped"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    networks:
      heidgaf:
        ipv4_address: 172.27.0.9
    deploy:
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 512m
        reservations:
          cpus: '1'
          memory: 256m

  # detector:
  #   build:
  #     context: ./dockerfiles
  #     dockerfile: Dockerfile.detector
  #   deploy:
  #     mode: "replicated"
  #     replicas: 6

networks:
  heidgaf:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1
