volumes:
  redis:
  heidgaf:

services:
  # TODO Currently not supported.
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis:/data

  heidgaf:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["heidgaf", "inspect", "-r", "/tmp/data", "-m", "xg"]
    volumes:
      - ./data/heicloud:/tmp/data
    memswap_limit: 42G
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 32g
        reservations:
          cpus: '4'
          memory: 24g
          # devices:
          # - driver: nvidia
          #   count: all
          #   capabilities: [gpu]
