kafka:
  brokers:
    - hostname: localhost
      port: 8097
    - hostname: localhost
      port: 8098
    - hostname: localhost
      port: 8099

  producer:
    transactional_id: my_transactional_id

  consumer:
    group_id: my_group
