kafka:
  brokers:
    - hostname: localhost
      port: 8097
    - hostname: localhost
      port: 8098
    - hostname: localhost
      port: 8099
  producer:
    transactional_id: your_transactional_id
    acks: all
    enable_idempotence: true
  consumer:
    group_id: your_group_id
    enable_auto_commit: false
    isolation_level: read_committed
