version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"


#version: '3'
#
#services:
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    hostname: localhost
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - "2181:2181"
#
#  kafka1:
#    image: confluentinc/cp-kafka:latest
#    hostname: localhost
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
#      KAFKA_MIN_INSYNC_REPLICAS: 2
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#
#  kafka2:
#    image: confluentinc/cp-kafka:latest
#    hostname: localhost
#    depends_on:
#      - zookeeper
#    ports:
#      - "9093:9093"
#    environment:
#      KAFKA_BROKER_ID: 2
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
#      KAFKA_MIN_INSYNC_REPLICAS: 2
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
#
#  kafka3:
#    image: confluentinc/cp-kafka:latest
#    hostname: localhost
#    depends_on:
#      - zookeeper
#    ports:
#      - "9094:9094"
#    environment:
#      KAFKA_BROKER_ID: 3
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
#      KAFKA_MIN_INSYNC_REPLICAS: 2
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
