services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.12.75-alpine
    container_name: clickhouse-server
    volumes:
      - ../../create_tables:/create_tables
      - ../../create_datatest_tables:/create_datatest_tables
      - ../../create_datatest_tables.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      heidgaf:
        ipv4_address: 172.27.0.11
    restart: "unless-stopped"
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.1 8123" ]
      interval: 10s
      timeout: 5s
      retries: 3
