apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      host: clickhouse-server
      port: 9000

      protocol: native

      username: default
      tlsSkipVerify: false
