apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      host: 172.27.0.11
      port: 9000

      protocol: native

      username: default
      tlsSkipVerify: false
