services:
  send-real-logs:
    build:
      context: ..
      dockerfile: docker/dockerfiles/Dockerfile.dev-real-logs
      network: host
    networks:
      docker_heidgaf:


networks:
  docker_heidgaf:
    external: true
