include:
  - "docker-compose.pipeline.yml"
  - "docker-compose.grafana-datatests.yml"

services:
  load-datasets:
    build:
      context: ..
      dockerfile: docker/dockerfiles/Dockerfile.test-datasets
      network: host
    depends_on:
      clickhouse-server:
        condition: service_healthy
    networks:
      heidgaf:
        ipv4_address: 172.27.0.200
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512m
        reservations:
          cpus: '1'
          memory: 256m

networks:
  heidgaf:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1
