include:
  - "docker-compose.monitoring.yml"

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.12.75-alpine
    container_name: clickhouse-server
    volumes:
      - ./create_tables:/create_tables
      - ./create_datatest_tables:/create_datatest_tables
      - ./create_datatest_tables.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      heidgaf:
        ipv4_address: 172.27.0.11
    restart: "unless-stopped"
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.1 8123" ]
      interval: 10s
      timeout: 5s
      retries: 3

  grafana:
    image: grafana/grafana:11.2.2-security-01
    container_name: grafana
    networks:
      heidgaf:
        ipv4_address: 172.27.0.13
    restart: "unless-stopped"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./datatests.json:/etc/grafana/provisioning/dashboards/datatests.json
      - ./grafana-provisioning/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana-provisioning/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 3000" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  heidgaf:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1
