include:
  - "docker-compose.kafka.yml"

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.12.75-alpine
    container_name: clickhouse-server
    networks:
      heidgaf:
        ipv4_address: 172.27.0.11
    restart: "unless-stopped"
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.1 8123" ]
      interval: 10s
      timeout: 5s
      retries: 3

  monitoring_agent:
    build:
      context: ..
      dockerfile: docker/dockerfiles/Dockerfile.monitoring
      network: host
    restart: "unless-stopped"
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      clickhouse-server:
        condition: service_healthy
    networks:
      heidgaf:
        ipv4_address: 172.27.0.12

networks:
  heidgaf:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1
