include:
  - "docker-compose.kafka.yml"

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.12.75-alpine
    container_name: clickhouse-server
    networks:
      heidgaf:
        ipv4_address: 172.27.0.11
    restart: "unless-stopped"
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.1 8123" ]
      interval: 10s
      timeout: 5s
      retries: 3

  grafana:
    image: grafana/grafana:11.2.2-security-01
    container_name: grafana
    networks:
      heidgaf:
        ipv4_address: 172.27.0.13
    restart: "unless-stopped"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-provisioning/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana-provisioning/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 3000" ]
      interval: 10s
      timeout: 5s
      retries: 3

  monitoring_agent:
    build:
      context: ..
      dockerfile: docker/dockerfiles/Dockerfile.monitoring
      network: host
    restart: "unless-stopped"
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      clickhouse-server:
        condition: service_healthy
      grafana:
        condition: service_healthy
    networks:
      heidgaf:
    #        ipv4_address: 172.27.0.12
    environment:
      - GROUP_ID=monitoring_agent
networks:
  heidgaf:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1
