services:
  send-real-logs:
    build:
      context: ..
      dockerfile: docker/dockerfiles/Dockerfile.dev-real-logs
      network: host
    networks:
      docker_heidgaf:
    memswap_limit: 768m
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512m
        reservations:
          cpus: '1'
          memory: 256m

networks:
  docker_heidgaf:
    external: true
