services:
  benchmark_test_run:
    image: localhost:5000/benchmark_test_run
    environment:
      - TEST_TYPE_NR=3
    networks:
      heidgaf:
    deploy:
      placement:
        constraints: [ node.hostname == heidgaf-1 ]
      restart_policy:
        condition: none

networks:
  heidgaf:
    external: true
