name: build_test_linux
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_test_linux:
    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.11",
                          "3.10",
        ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup py-${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements/requirements.*.txt

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/requirements.dev.txt -r requirements/requirements.detector.txt -r requirements/requirements.logcollector.txt -r requirements/requirements.prefilter.txt -r requirements/requirements.inspector.txt -r requirements/requirements.logserver.txt

      - name: Test
        run: |
          python -m unittest discover tests
