name: pre-commit

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.0

    - name: Set up Python 3.8
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.11'

    - name: Get pip cache path
      id: get-pip-path
      run: |
          id=$(echo ${{ env.pythonLocation }} | sed 's/\/bin//g')
          echo "name=id::$id" >> $GITHUB_OUTPUT
    - name: Pip cache
      uses: actions/cache@v3
      id: pip-cache
      with:
        path: ${{ steps.get-pip-path.outputs.id }}
        key: ${{ steps.get-pip-path.outputs.id }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements/requirements-dev.txt') }}-${{ hashFiles('requirements/requirements-logcollector.txt') }}-${{ hashFiles('requirements/requirements-detector.txt') }}-${{ hashFiles('requirements/requirements-prefilter.txt') }}-${{ hashFiles('requirements/requirements-inspector.txt') }}

    - name: Install requirements
      if: steps.pip-cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements/requirements-dev.txt -r requirements/requirements.detector.txt -r requirements/requirements.logcollector.txt -r requirements/requirements.prefilter.txt -r requirements/requirements.inspector.txt

    - name: Cache pre-commit hooks
      uses: actions/cache@v4.0.2
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit
      run: pre-commit run --all-files
